[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/create-pix"
  to     = "/.netlify/functions/create-pix"
  status = 200

[[redirects]]
  from = "/api/zuck-webhook"
  to = "/.netlify/functions/zuck-webhook"
  status = 200
  methods = ["POST", "OPTIONS"]

[[redirects]]
  from = "/api/tx/:id"
  to = "/.netlify/functions/tx?id=:id"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
