[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/create-pix"
  to     = "/.netlify/functions/create-pix"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
